services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: straysafe
    shm_size: 256mb

  backend:
    build:
      dockerfile: backend/Dockerfile
    ports:
      - 8080:8080
    environment:
      DSN: postgres://postgres:password@db:5432/straysafe
